import React from 'react';
import HeaderAdSenseCompliant from '@/components/HeaderAdSenseCompliant';
import FooterAdSenseCompliant from '@/components/FooterAdSenseCompliant';
import SEOMetadata from '@/components/SEOMetadata';
import PlayStoreCompliantDisclaimer from '@/components/PlayStoreCompliantDisclaimer';
import PageBreadcrumb from '@/components/PageBreadcrumb';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { HelpCircle, FileText, Shield, Download, Clock, Globe } from 'lucide-react';

const FAQ = () => {
  const faqCategories = [
    {
      title: "General Questions",
      icon: HelpCircle,
      faqs: [
        {
          question: "What is DocuCreator Pro?",
          answer: "DocuCreator Pro is an AI-powered online tool that helps you create professional legal documents, contracts, and agreements instantly. Our platform uses advanced AI technology to generate legally formatted documents that you can customize and download for free."
        },
        {
          question: "Is DocuCreator Pro free to use?",
          answer: "Yes, DocuCreator Pro is completely free to use. You can create unlimited documents, download them as PDFs, and use them for personal or business purposes without any charges."
        },
        {
          question: "Do I need to create an account to use DocuCreator Pro?",
          answer: "No, you don't need to create an account. DocuCreator Pro works instantly without any registration or sign-up process. Simply select your document type, fill in the details, and download your document."
        },
        {
          question: "Which languages are supported?",
          answer: "DocuCreator Pro currently supports English and Hindi languages for document generation. We're working on adding more regional languages soon."
        }
      ]
    },
    {
      title: "Document Types",
      icon: FileText,
      faqs: [
        {
          question: "What types of documents can I create?",
          answer: "You can create various legal documents including: Rent Agreements, Sale Deeds, Power of Attorney, Affidavits, Business Contracts, NDAs (Non-Disclosure Agreements), Employment Contracts, Partnership Deeds, Will/Testament, Loan Agreements, and many more."
        },
        {
          question: "Are the documents legally valid?",
          answer: "The documents generated by DocuCreator Pro are formatted according to Indian legal standards. However, for documents requiring legal enforcement, we recommend getting them notarized or registered with the appropriate authorities as per local laws."
        },
        {
          question: "Can I customize the documents?",
          answer: "Yes, all documents are fully customizable. You can edit the generated content, add or remove clauses, and modify the formatting before downloading the final document."
        },
        {
          question: "What document formats are available for download?",
          answer: "Documents are available for download in PDF format, which is universally compatible and maintains professional formatting across all devices and platforms."
        }
      ]
    },
    {
      title: "Privacy & Security",
      icon: Shield,
      faqs: [
        {
          question: "Is my data safe with DocuCreator Pro?",
          answer: "Yes, we take data privacy very seriously. All document generation happens in your browser, and we don't store any personal information or document content on our servers. Your data remains completely private."
        },
        {
          question: "Do you share my information with third parties?",
          answer: "No, we never share, sell, or distribute your personal information or document data to any third parties. Your privacy is our top priority."
        },
        {
          question: "Is the connection secure?",
          answer: "Yes, DocuCreator Pro uses HTTPS encryption to ensure all data transmission is secure and protected from unauthorized access."
        }
      ]
    },
    {
      title: "Downloads & Usage",
      icon: Download,
      faqs: [
        {
          question: "How do I download my document?",
          answer: "After filling in your document details, click the 'Generate Document' button. Once your document is ready, you'll see a 'Download PDF' button. Click it to save the document to your device."
        },
        {
          question: "Can I edit a document after downloading?",
          answer: "The downloaded PDF is a fixed document. If you need to make changes, we recommend going back to the document form, making your edits, and generating a new document."
        },
        {
          question: "Is there a limit on how many documents I can create?",
          answer: "No, there's no limit. You can create as many documents as you need, completely free of charge."
        }
      ]
    },
    {
      title: "Technical Support",
      icon: Clock,
      faqs: [
        {
          question: "The document is not generating. What should I do?",
          answer: "Please ensure all required fields are filled correctly. If the issue persists, try refreshing the page or using a different browser. You can also contact our support team for assistance."
        },
        {
          question: "Which browsers are supported?",
          answer: "DocuCreator Pro works on all modern browsers including Chrome, Firefox, Safari, Edge, and Opera. For the best experience, we recommend using the latest version of your browser."
        },
        {
          question: "Does DocuCreator Pro work on mobile devices?",
          answer: "Yes, DocuCreator Pro is fully responsive and works seamlessly on smartphones, tablets, and desktop computers. You can also download our Android app for an enhanced mobile experience."
        }
      ]
    },
    {
      title: "Legal & Compliance",
      icon: Globe,
      faqs: [
        {
          question: "Are the documents compliant with Indian law?",
          answer: "Our document templates are designed following Indian legal standards and formats. However, legal requirements may vary by state and specific circumstances. For critical legal matters, we recommend consulting with a qualified legal professional."
        },
        {
          question: "Can I use these documents for official purposes?",
          answer: "Yes, you can use our documents for various official purposes. For documents requiring legal validity (like property agreements), you may need to get them notarized or registered with the Sub-Registrar office as per applicable laws."
        },
        {
          question: "Do you provide legal advice?",
          answer: "No, DocuCreator Pro is a document generation tool and does not provide legal advice. For specific legal queries or complex matters, please consult with a qualified lawyer or legal professional."
        }
      ]
    }
  ];

  // Flatten FAQs for structured data
  const allFaqs = faqCategories.flatMap(category => 
    category.faqs.map(faq => ({
      question: faq.question,
      answer: faq.answer
    }))
  );

  return (
    <div className="flex flex-col min-h-screen">
      <SEOMetadata 
        title="FAQ - Frequently Asked Questions | DocuCreator Pro"
        description="Find answers to common questions about DocuCreator Pro. Learn how to create legal documents, download PDFs, and use our AI-powered document generator."
        keywords="DocuCreator Pro FAQ, legal document questions, document generator help, how to create legal documents, free document maker FAQ"
        canonicalUrl="/faq"
        breadcrumbs={[
          { name: "Home", url: "/" },
          { name: "FAQ", url: "/faq" }
        ]}
        faqItems={allFaqs}
      />
      
      <HeaderAdSenseCompliant />
      <PageBreadcrumb items={[{ label: "FAQ" }]} />
      
      <main className="flex-grow bg-gradient-to-b from-white to-legal-light">
        <div className="container mx-auto px-4 py-8 md:py-12">
          {/* Hero Section */}
          <div className="text-center mb-12">
            <h1 className="text-3xl md:text-4xl font-serif font-bold text-legal-navy mb-4">
              Frequently Asked Questions
            </h1>
            <p className="text-lg text-legal-gray max-w-2xl mx-auto">
              Find answers to common questions about DocuCreator Pro and how to create professional legal documents online.
            </p>
          </div>

          {/* FAQ Categories */}
          <div className="max-w-4xl mx-auto space-y-8">
            {faqCategories.map((category, categoryIndex) => (
              <div key={categoryIndex} className="bg-white rounded-lg shadow-md p-6">
                <div className="flex items-center gap-3 mb-6">
                  <div className="p-2 bg-legal-navy/10 rounded-lg">
                    <category.icon className="w-6 h-6 text-legal-navy" />
                  </div>
                  <h2 className="text-xl font-semibold text-legal-navy">
                    {category.title}
                  </h2>
                </div>
                
                <Accordion type="single" collapsible className="w-full">
                  {category.faqs.map((faq, faqIndex) => (
                    <AccordionItem key={faqIndex} value={`${categoryIndex}-${faqIndex}`}>
                      <AccordionTrigger className="text-left text-legal-navy hover:text-legal-accent">
                        {faq.question}
                      </AccordionTrigger>
                      <AccordionContent className="text-legal-gray leading-relaxed">
                        {faq.answer}
                      </AccordionContent>
                    </AccordionItem>
                  ))}
                </Accordion>
              </div>
            ))}
          </div>

          {/* Contact Section */}
          <div className="text-center mt-12 p-8 bg-legal-navy/5 rounded-lg max-w-2xl mx-auto">
            <h2 className="text-2xl font-serif font-bold text-legal-navy mb-4">
              Still Have Questions?
            </h2>
            <p className="text-legal-gray mb-6">
              Can't find the answer you're looking for? Our support team is here to help.
            </p>
            <a 
              href="/contact" 
              className="inline-block bg-legal-navy text-white px-6 py-3 rounded-lg hover:bg-legal-accent transition-colors"
            >
              Contact Support
            </a>
          </div>
        </div>
        
        <PlayStoreCompliantDisclaimer />
      </main>
      
      <FooterAdSenseCompliant />
    </div>
  );
};

export default FAQ;
